---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.6
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: publish-image
  image: plugins/docker
  settings:
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "longhornio/upgrade-responder"
    tag: "${DRONE_BRANCH}-head"
    username:
      from_secret: docker_username
  when:
    event:
    - push

- name: publish-tagged-image
  image: plugins/docker
  settings:
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "longhornio/upgrade-responder"
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.longhorn.io
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

