FROM golang:1.17-alpine

RUN apk -U add bash git gcc musl-dev docker vim less file curl wget ca-certificates
RUN go get -u golang.org/x/lint/golint

ENV DAPPER_ENV REPO TAG DRONE_TAG
ENV DAPPER_SOURCE /go/src/github.com/longhorn/upgrade-responder/
ENV DAPPER_OUTPUT ./bin ./dist ./package
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
