#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-longhornio}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

cp ../bin/upgrade-responder-* .
cp ../geodb/GeoLite2-City.mmdb .

IMAGE=${REPO}/upgrade-responder:${TAG}
buildx build --load -t ${IMAGE} .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
