#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-longhornio}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

cp ../bin/upgrade-responder .
cp ../geodb/GeoLite2-City.mmdb .

IMAGE=${REPO}/upgrade-responder:${TAG}
docker build -t ${IMAGE} .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
